config/routes.rb
Rails.application.routes.draw do

  get 'cita_medica/crear'
  post 'cita_medica/crear'

  get 'cita_medica/efectuar'
  post 'cita_medica/efectuar'

  get 'cita_medica/modificar'
  post 'cita_medica/modificar'
  
  get 'cita_medica/visualizar'

  get 'cita_medica/agregar_respuesta'
  post 'cita_medica/agregar_respuesta'

  get 'paciente/agregar'
  post 'paciente/agregar'

  get 'paciente/actualizar'
  post 'paciente/actualizar'
  
  get 'paciente/agregar_inr'

  get 'paciente/visualizar'

  get 'omniauth_callbacks/google_oauth2'

  get 'horario/modificar'
  post 'horario/modificar'
  
  get 'horario/cargar'

  get 'usuario/agregar'
  post 'usuario/agregar'

  get 'usuario/actualizar'
  post 'usuario/actualizar'

  get 'usuario/visualizar'

  get 'usuario/autorizar'
  post 'usuario/autorizar'
  
  get 'usuario/desactivar'
  
  get 'usuario/cambiar'
  post 'usuario/cambiar'

  devise_for :cuenta_usuarios, :controllers => { :omniauth_callbacks => "callbacks" }

  get 'medico_internista/contenido'

  get 'administracion/contenido'
  
  get 'principal/contenido'
  
  root :to => 'principal#contenido'
  

  
  
end

app/models/anticoagulante.rb
class Anticoagulante < ActiveRecord::Base
  has_many :prescripcions, class_name: Prescripcion
end

app/models/cita_icd.rb
class CitaIcd < ActiveRecord::Base
  belongs_to :icds, class_name: Icd
  belongs_to :cita_medicas, class_name: CitaMedica
end

app/models/cita_medica.rb
class CitaMedica < ActiveRecord::Base
  belongs_to :pacientes, class_name: Paciente
  belongs_to :cuenta_usuarios, class_name: CuentaUsuario
  
  has_many :cita_icds, class_name: CitaIcd, foreign_key: :cita_medicas_id
  has_many :inr_pacientes, class_name: InrPaciente, foreign_key: :cita_medicas_id
  has_many :pregunta_cita, class_name: PreguntaCita, foreign_key: :cita_medicas_id
  has_one :respuesta_cita, class_name: RespuestaCita, foreign_key: :cita_medicas_id
  has_one :observacion_medicas, class_name: ObservacionMedica, foreign_key: :cita_medicas_id
  has_one :prescripcions,class_name: Prescripcion , through: :respuesta_cita
end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
  has_many :pacientes, class_name: Paciente, foreign_key: :ciudads_id
  has_many :cuenta_usuarios, class_name: CuentaUsuario, foreign_key: :ciudads_id
end

app/models/cuenta_usuario.rb
class CuentaUsuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  
  belongs_to :rols, class_name: Rol
  belongs_to :estado_civils, class_name: EstadoCivil
  belongs_to :tipo_documentos, class_name: TipoDocumento
  belongs_to :ciudads, class_name: Ciudad
  
  def self.from_omniauth(auth)
    where(["email = ? and estado < ? ", auth.info.email ,3]).first
  end
  
end

app/models/dia_asociado.rb
class DiaAsociado < ActiveRecord::Base
  has_many :prescripcion_diaria, class_name: PrescripcionDiaria
end

app/models/estado_civil.rb
class EstadoCivil < ActiveRecord::Base
end

app/models/icd.rb
class Icd < ActiveRecord::Base
  has_many :cita_icds, class_name: CitaIcd, foreign_key: :icds_id
end

app/models/inr_paciente.rb
class InrPaciente < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  has_many :respuesta_cita, class_name: RespuestaCita, through: :cita_medicas
end

app/models/laboratorio.rb
class Laboratorio < ActiveRecord::Base
  belongs_to :pacientes, class_name: Paciente
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  belongs_to :tipo_documentos, class_name: TipoDocumento
  belongs_to :estado_civils, class_name: EstadoCivil
  belongs_to :patologia, class_name: Patologia
  belongs_to :ciudads, class_name: Ciudad
  
  has_many :cita_medicas, class_name: CitaMedica, foreign_key: :pacientes_id
  has_many :laboratorios,class_name: Laboratorio, foreign_key: :pacientes_id
  has_many :antecedente_paciente, class_name: AntecedentePaciente, foreign_key: :pacientes_id
  has_many :prescripcions,class_name: Prescripcion , through: :cita_medicas
  has_many :inr_paciente, class_name: InrPaciente, through: :cita_medicas
  
  has_attached_file :avatar, :styles => { :medium => "#300x300>" }, :default_url => "/images/:style/missing.png"
  
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  validates_attachment_presence :avatar
  
  def ultimaCita
    cita_medicas.where(["generico = ? and estado = ? and tipo = ?", false, 2, "Presencial"]).last
  end
  
  def ultimaVisita
    cita_medicas.where(["generico = ? and estado > ? and tipo = ?", false, 1, "Domiciliaria"]).last
  end
  
end

app/models/patologia.rb
class Patologia < ActiveRecord::Base
end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  
  has_many :pregunta_cita, class_name: PreguntaCita, foreign_key: :pregunta_id
  
end

app/models/pregunta_cita.rb
class PreguntaCita < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  belongs_to :pregunta, class_name: Pregunta
end

app/models/prescripcion.rb
class Prescripcion < ActiveRecord::Base
  belongs_to :respuesta_cita, class_name: RespuestaCita
  belongs_to :anticoagulantes, class_name: Anticoagulante
  
  has_many :prescripcion_diaria, class_name: PrescripcionDiaria, foreign_key: :prescripcions_id
  
end

app/models/respuesta_cita.rb
class RespuestaCita < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  belongs_to :cuenta_usuarios, class_name: CuentaUsuario
  
  has_one :prescripcions, class_name: Prescripcion
  
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
end

app/models/tipo_documento.rb
class TipoDocumento < ActiveRecord::Base
end

app/controllers/medico_internista_controller.rb
class MedicoInternistaController < ApplicationController
  def contenido
    if @medico
      busqueda=params[:nombreP]
      @misCitas=CitaMedica.where(["estado = ? and cuenta_usuarios_id = ?",1, current_cuenta_usuario.id])
    else
      redirect_to controller: "principal", action: "contenido"
    end
  end

end

app/helpers/medico_internista_helper.rb
module MedicoInternistaHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/medico_internista/_menu.html.erb
<li><%= link_to "Pacientes", {controller: "paciente", action: "visualizar"}%></li>
<li><%= link_to "Mis citas", {controller: "cita_medica", action: "visualizar", usuario: current_cuenta_usuario.email} %></li>
<li><%= link_to "Modificar datos personales", {controller: "usuario", action: "actualizar"} %></li>
<li><%= link_to "Cerrar Sesion", destroy_cuenta_usuario_session_path, method: :delete, id: "sign_out"  %></li>

app/views/medico_internista/_menu_at.html.erb
<li><%=link_to "Agregar datos", {controller: "usuario", action: "agregar"} %></li>
<li><%= link_to "Cerrar Sesion", destroy_cuenta_usuario_session_path, method: :delete, id: "sign_out" ,class: "list-group-item list-group-item-danger"%></li>

app/views/medico_internista/contenido.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Mis citas</h3>
	</div>
	<div class="panel-body">
		<% @misCitas.each do |t|%>
			<div class="row">
				<div class="col-md-10">
					<strong>Fecha: </strong> <%= t.fecha%> - <%= t.hora_ini%>
					<% if t.fecha>Date.current%>
						<span class="label label-info">Proximamente</span>
					<% elsif t.fecha<Date.current%>
						<span class="label label-danger">Vencida</span>
					<% else%>
						<span class="label label-warning">Hoy</span>
					<% end%>
					<br />
					<strong>Paciente:</strong><%= t.pacientes.nombre+' '+t.pacientes.apellido%>
				</div>
				<div class="col-md-2">
					<div class="btn-group btn-group-justified" role="group">
						<div class="btn-group" role="group">
							<%= link_to "Efectuar", {controller: "cita_medica", action: "efectuar", cita: t.id}, class: "btn btn-success"%>
						</div>
					</div>
				</div>
			</div>
		<% end%>
	</div>
</div>