config/routes.rb
Rails.application.routes.draw do

  get 'cita_medica/crear'
  post 'cita_medica/crear'

  get 'cita_medica/efectuar'
  post 'cita_medica/efectuar'

  get 'cita_medica/modificar'
  post 'cita_medica/modificar'
  
  get 'cita_medica/visualizar'

  get 'cita_medica/agregar_respuesta'
  post 'cita_medica/agregar_respuesta'

  get 'paciente/agregar'
  post 'paciente/agregar'

  get 'paciente/actualizar'
  post 'paciente/actualizar'
  
  get 'paciente/agregar_inr'

  get 'paciente/visualizar'

  get 'omniauth_callbacks/google_oauth2'

  get 'horario/modificar'
  post 'horario/modificar'
  
  get 'horario/cargar'

  get 'usuario/agregar'
  post 'usuario/agregar'

  get 'usuario/actualizar'
  post 'usuario/actualizar'

  get 'usuario/visualizar'

  get 'usuario/autorizar'
  post 'usuario/autorizar'
  
  get 'usuario/desactivar'
  
  get 'usuario/cambiar'
  post 'usuario/cambiar'

  devise_for :cuenta_usuarios, :controllers => { :omniauth_callbacks => "callbacks" }

  get 'medico_internista/contenido'

  get 'administracion/contenido'
  
  get 'principal/contenido'
  
  root :to => 'principal#contenido'
  

  
  
end

app/models/anticoagulante.rb
class Anticoagulante < ActiveRecord::Base
  has_many :prescripcions, class_name: Prescripcion
end

app/models/cita_icd.rb
class CitaIcd < ActiveRecord::Base
  belongs_to :icds, class_name: Icd
  belongs_to :cita_medicas, class_name: CitaMedica
end

app/models/cita_medica.rb
class CitaMedica < ActiveRecord::Base
  belongs_to :pacientes, class_name: Paciente
  belongs_to :cuenta_usuarios, class_name: CuentaUsuario
  
  has_many :cita_icds, class_name: CitaIcd, foreign_key: :cita_medicas_id
  has_many :inr_pacientes, class_name: InrPaciente, foreign_key: :cita_medicas_id
  has_many :pregunta_cita, class_name: PreguntaCita, foreign_key: :cita_medicas_id
  has_one :respuesta_cita, class_name: RespuestaCita, foreign_key: :cita_medicas_id
  has_one :observacion_medicas, class_name: ObservacionMedica, foreign_key: :cita_medicas_id
  has_one :prescripcions,class_name: Prescripcion , through: :respuesta_cita
end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
  has_many :pacientes, class_name: Paciente, foreign_key: :ciudads_id
  has_many :cuenta_usuarios, class_name: CuentaUsuario, foreign_key: :ciudads_id
end

app/models/cuenta_usuario.rb
class CuentaUsuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  
  belongs_to :rols, class_name: Rol
  belongs_to :estado_civils, class_name: EstadoCivil
  belongs_to :tipo_documentos, class_name: TipoDocumento
  belongs_to :ciudads, class_name: Ciudad
  
  def self.from_omniauth(auth)
    where(["email = ? and estado < ? ", auth.info.email ,3]).first
  end
  
end

app/models/dia_asociado.rb
class DiaAsociado < ActiveRecord::Base
  has_many :prescripcion_diaria, class_name: PrescripcionDiaria
end

app/models/estado_civil.rb
class EstadoCivil < ActiveRecord::Base
end

app/models/icd.rb
class Icd < ActiveRecord::Base
  has_many :cita_icds, class_name: CitaIcd, foreign_key: :icds_id
end

app/models/inr_paciente.rb
class InrPaciente < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  has_many :respuesta_cita, class_name: RespuestaCita, through: :cita_medicas
end

app/models/laboratorio.rb
class Laboratorio < ActiveRecord::Base
  belongs_to :pacientes, class_name: Paciente
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  belongs_to :tipo_documentos, class_name: TipoDocumento
  belongs_to :estado_civils, class_name: EstadoCivil
  belongs_to :patologia, class_name: Patologia
  belongs_to :ciudads, class_name: Ciudad
  
  has_many :cita_medicas, class_name: CitaMedica, foreign_key: :pacientes_id
  has_many :laboratorios,class_name: Laboratorio, foreign_key: :pacientes_id
  has_many :antecedente_paciente, class_name: AntecedentePaciente, foreign_key: :pacientes_id
  has_many :prescripcions,class_name: Prescripcion , through: :cita_medicas
  has_many :inr_paciente, class_name: InrPaciente, through: :cita_medicas
  
  has_attached_file :avatar, :styles => { :medium => "#300x300>" }, :default_url => "/images/:style/missing.png"
  
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  validates_attachment_presence :avatar
  
  def ultimaCita
    cita_medicas.where(["generico = ? and estado = ? and tipo = ?", false, 2, "Presencial"]).last
  end
  
  def ultimaVisita
    cita_medicas.where(["generico = ? and estado > ? and tipo = ?", false, 1, "Domiciliaria"]).last
  end
  
end

app/models/patologia.rb
class Patologia < ActiveRecord::Base
end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  
  has_many :pregunta_cita, class_name: PreguntaCita, foreign_key: :pregunta_id
  
end

app/models/pregunta_cita.rb
class PreguntaCita < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  belongs_to :pregunta, class_name: Pregunta
end

app/models/prescripcion.rb
class Prescripcion < ActiveRecord::Base
  belongs_to :respuesta_cita, class_name: RespuestaCita
  belongs_to :anticoagulantes, class_name: Anticoagulante
  
  has_many :prescripcion_diaria, class_name: PrescripcionDiaria, foreign_key: :prescripcions_id
  
end

app/models/respuesta_cita.rb
class RespuestaCita < ActiveRecord::Base
  belongs_to :cita_medicas, class_name: CitaMedica
  belongs_to :cuenta_usuarios, class_name: CuentaUsuario
  
  has_one :prescripcions, class_name: Prescripcion
  
end

app/models/rol.rb
class Rol < ActiveRecord::Base
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
end

app/models/tipo_documento.rb
class TipoDocumento < ActiveRecord::Base
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/layouts/_menu.html.erb
	<%if @autorizado%>
		<%= render 'medico_internista/menu_at'%>
	<% elsif @admin%>
		<%= render 'administracion/menu'%>
	<% elsif @medico%>
		<%= render 'medico_internista/menu'%>
	<% elsif @paramedico%>
		<%= render 'paramedico/menu'%>
	<% else%>
		<%= render 'principal/menu'%>
	<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Clinica Axon de Anticoagulación</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<script type="text/javascript"> $(document).ready(function () { $('.dropdown-toggle').dropdown(); }); </script>


	</head>
	<body<%= " id=#{controllername}" if controllername %>>
			<% unless controllername=="inicio" %>
			<div id="wrapper">
				<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
					<div class="navbar-header">
                		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		                    <span class="sr-only">Toggle navigation</span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
                		</button>
                		<%= link_to image_tag("CACBrand.png"), {controller: "/principal", action: "contenido"}, class: "navbar-brand" %>
            		</div> <!-- /.navbar-header -->
            		
					<ul class="nav navbar-nav navbar-top-links navbar-right">				
				        <li class="dropdown">
	                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                       	<i class="fa fa-bell fa-fw"></i>   Alertas  <i class="fa fa-caret-down"></i>
	                        </a>
	                        <ul class="dropdown-menu dropdown-alerts">
		                        <li>
		                              <a href="#">
		                                  <div>
		                                      <i class="fa fa-bell fa-fw"></i> Paciente uno
		                                      <span class="pull-right text-muted small">Hace 5 minutos</span>
		                                  </div>
		                              </a>
		                          </li>
	                       		  <li class="divider"></li>
		                          <li>
		                              <a href="#">
		                                  <div>
		                                      <i class="fa fa-bell fa-fw"></i> Paciente dos
		                                      <span class="pull-right text-muted small">Hace 10 minutos</span>
		                                  </div>
		                              </a>
		                          </li>
		                      </ul><!--dropdown-menu-items-->
                      	</li><!-- Dropdownalerts-->
                      	
					</ul><!--nav Toplinks-->
					<div class="navbar-default sidebar" role="navigation">
                		<div class="sidebar-nav navbar-collapse">
                    		<ul class="nav" id="side-menu">
                    			<li class="sidebar-user"> 
                           					<div style="float:left; padding-right: 8px"><img src="<%= current_cuenta_usuario.link_foto %>" class="img-circle" height="50"></div>
                            				<div><h6><%= current_cuenta_usuario.nombre + " " + current_cuenta_usuario.apellido %> <br/><small>Cargo</small></h6>
                            			</div>
                  
                       			 </li>		
								<%= render 'layouts/menu'%>
                    		</ul><!--nav-->
                    	</div><!--sidebarnav collapse-->
                   	</div><!--Navbardefault-->
				</nav>

				 <div id="page-wrapper">
					<div class="container-fluid">
						<% if notice%>
						    <div class="alert alert-info alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <%= notice %>
                            </div>
						<% end %>	
						<% if alert%>
						  <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <%= alert %>
                          </div>
						<% end %>
						<%= yield %>
					</div><!--Containerfluid -->
				</div><!--PageWrapper -->
			</div><!--wrapper --> 
				<% else %>
					<div class="container">
						<div class="vspacer2"></div>
						<% if alert%>
						  <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <%= alert %>
                          </div>
						<% end %>
				</div>
				<%= yield %>
			<% end %>
		</div>
	</body>
</html>